"""
The canonical tagging vocabulary for the functionality check.

Supplied by the product owner and mirrored in Pylon's dropdowns
(Sep 2026). Grouped entries are stored as their full display string
('Group : Item' / 'Group - Item') because that is what a correct
suggestion must be copied from, verbatim. Ships as code so every
deployment carries the same list and a change is a reviewed commit.
"""

FUNCTIONALITIES = [
    'Contract Creation : Template Contract flow',
    'Contract Creation : Upload third-party paper flow',
    'Contract Creation : Third Party paper - Intake form issues',
    'Contract Creation : Express Contracts flow',
    'Contract Creation : Upload executed contracts flow',
    'Contract Creation : Send for Signature flow',
    'Contract Creation : Campaigns',
    'Contract Creation : Stamp paper',
    'Contract Creation : Contract packets',
    'Access Control : Team based permissions',
    'Access Control : Contract Type - Access Control [Global]',
    'Access Control : Invite/remove users',
    'Access Control : Team Deletion',
    'Workflow Manager : Signature Settings',
    'Workflow Manager : Sign Order',
    'Workflow Manager : Email Settings',
    'Workflow Manager : Conditional Signatures',
    'Workflow Manager : Conditional Approvals',
    'Workflow Manager : Conditional Reviews',
    'Workflow Manager : Template Document',
    'Workflow Manager : Set Up Questionnaire',
    'Workflow Manager : Questionnaire Modifications',
    'Workflow Manager : Questionnaire Modifications - CP',
    'Workflow Manager : Template Publish',
    'Workflow Manager : Counterparty Settings',
    'Workflow Manager : Creator Party Settings',
    'Workflow Manager : Template Versions',
    'Workflow Manager : Linking contract type',
    'Workflow Manager : Skip CP redlining',
    'Workflow Manager : Contract title',
    'Workflow Manager : Default currency',
    'Workflow Manager : Campaign setup',
    'Workflow Manager : Email attachment formats',
    'Workflow Manager : Download permission for counterparty',
    'Workflow Manager : Approval Watermark',
    'Workflow Manager : Archive Workflow',
    'Workflow Manager : Delete Workflows',
    'Workflow Manager : OTP Preferences',
    'Workflow Manager : Base Template',
    'Workflow Manager : Sequential and parallel approval flows',
    'Workflow Manager : Multi-approver (routing) configurations',
    'Workflow Manager : Condition Library',
    'Workflow Manager : Duplicate Workflow',
    'Workflow Manager : Computation Library',
    'Workflow Manager : Resetting of approvals',
    'Workflow Manager : Blocked Actions on approvals',
    'Workflow Manager : Pre-send and pre-sign approvals',
    'Workflow Manager : WF Settings',
    'Workflow Manager : Auto Sign',
    'Workflow Manager : Signature Reminders',
    'Contract Type Settings : Entity association',
    'Contract Type Settings : Contract Expiration/Execution Emails',
    'Contract Type Settings : Signature Settings',
    'Contract Type Settings : Sign Recipients',
    'Contract Type Settings : Email',
    'Metadata : Metadata Mapping',
    'Metadata : Issues with Sections',
    'Metadata : Global Metadata',
    'Metadata : Update Metadata Fields',
    'Clause Library : Clause Library issues/concern',
    'Performance : Session timeout',
    'Performance : Slowness in app',
    'Performance : Page not loading',
    'User Exp (UI/UX) : Intuitive navigation / Accessibility improvements',
    'Integrations : Salesforce (SFDC)',
    'Integrations : HubSpot',
    'Integrations : Google Drive',
    'Integrations : OneDrive',
    'Integrations : Sharepoint',
    'Integrations : Dropbox',
    'Integrations : Box',
    'Integrations : Communication - Slack',
    'Integrations : Communication - MS Teams',
    'Integrations : Monday',
    'Integrations : JIRA / Google Forms',
    'Integrations : Esign -Docusign',
    'Integrations : APIs & Webhooks',
    'Integrations : Gmail/Outlook plugins',
    'Integrations : HRMS - Greenhouse',
    'Contract Summary Page : Share contract with Counterparty',
    'Contract Summary Page : Downloadable audit reports',
    'Contract Summary Page : Preview Contract',
    'Contract Summary Page : Contract Title updation',
    'Contract Summary Page : Contract status',
    'Contract Summary Page : Void Contract',
    'Contract Summary Page : Contract Versions',
    'Contract Summary Page : Move to Redlining',
    'Contract Summary Page : Send for Signature',
    'Contract Summary Page : Notes',
    'Contract Summary Page : Metadata',
    'Contract Summary Page : Download Contract',
    'Contract Summary Page : Upload Contract',
    'Contract Summary Page : Activity logs',
    'Contract Summary Page : Linked contracts',
    'Contract Summary Page : Supporting Documents',
    'Contract Summary Page : Update Party information',
    'Contract Summary Page : Intake form/Questionnaire responses',
    'Contract Summary Page : Ad-hoc approvals',
    'Contract Summary Page : PDF to DOCX conversion',
    'Contract Summary Page : Business User',
    'Contract Summary Page : Legal User',
    'Contract Summary Page : Counterparty Quesstionaire responses',
    'Contract Summary Page : Compare Contracts',
    'Contract Summary Page : Request Review',
    'Contract Summary Page : Contract Merging',
    'Contract Summary Page : Contract specific action (three dots)',
    'Contract Summary Page : Re-assignment of approvals',
    'Contract Summary Page : Status Card',
    'Contract Summary Page : Prepare for Signature',
    'Contract Summary Page : Contract Summary',
    'Manage Counterparties : Adding/updating Counterparty',
    'Manage Counterparties : Bulk Add Counterparty from UI',
    'Manage Counterparties : Merge Counterparty',
    'Manage Counterparties : Archive Counterparty',
    'Login : User authentication (Oauth)',
    'Login : Workspace expiry',
    'Login : Password reset',
    'Login : User authentication (SAML)',
    'Login : Demo Access',
    'Login : Login',
    'Login : Captcha Failing',
    'WS Creation : Trial workspace Creation',
    'WS Creation : QA Workspace Creation',
    'WS Creation : Trial extensions',
    'Bulk Tasks : Bulk Approval Setup',
    'Bulk Tasks : Migration support (Other CLM -> SpotDraft)',
    'Bulk Tasks : Bulk SDC Extract',
    'Bulk Tasks : Bulk Access updates',
    'Bulk Tasks : Bulk contract import',
    'Bulk Tasks : Bulk Filters update',
    'Bulk Tasks : Bulk uploading contracts',
    'Bulk Tasks : Bulk Signature Setup',
    'Bulk Tasks : Bulk update Metadata',
    'Bulk Tasks : Bulk Add entity',
    'Bulk Tasks : Duplicate Prod Workspace',
    'Bulk Tasks : Export Licensed Users List',
    'Bulk Tasks : Approval Reassignment',
    'Bulk Tasks : Contract Type Update',
    'Bulk Tasks : Contract Entity Update',
    'Bulk Tasks : Add Tags',
    'Bulk Tasks : Duplicate QA Workspace',
    'Repository : One time report',
    'Repository : Recurring Report',
    'Repository : Filters',
    'Repository : Bulk actions',
    'Repository : Saved views',
    'Repository : Manage Columns',
    'Repository : Sorting',
    'Repository : Delete Contract',
    'Repository : Restore Contract',
    'Repository : Add tags',
    'Repository : Repository',
    'Repository : Search functionality',
    'AI : Ask AI',
    'AI : VerifAI',
    'AI : Summary of Changes / AI revisions',
    'AI : AI Module/AI Package',
    'AI : AI Extraction - SDC',
    'AI : AI Drafting',
    'AI : AI Summary in Signing flow',
    'AI : SDC Lite',
    'AI : Import VerifAI guides',
    'AI : MCP Server',
    'AI : Sidebar',
    'Clickthrough & Legal Hub : Agreement Create and Publish',
    'Clickthrough & Legal Hub : Agreement Settings',
    'Clickthrough & Legal Hub : Agreement Custom Code',
    'Clickthrough & Legal Hub : Agreement Repository',
    'Clickthrough & Legal Hub : Legal Hub Pages',
    'Clickthrough & Legal Hub : Legal Hub Domain Settings',
    'Clickthrough & Legal Hub : Legal Hub Custom Code',
    'Clickthrough & Legal Hub : Clickthrough Packet Setup',
    'Clickthrough & Legal Hub : Clickthrough Repository',
    'Clickthrough & Legal Hub : Clickthrough Technical Implementation',
    'Clickthrough & Legal Hub : Clickthrough Reports & Analytics',
    'Contract Analytics : Analytics Views',
    'Contract Analytics : Card Download',
    'Contract Analytics : Analytics Filters',
    'Contract Analytics : Data Sync Issues',
    'Notifications : Email Notifications',
    'Notifications : Native Slack Notification',
    'Notifications : Native MS Teams Notification',
    'Notifications : Task notifications',
    'Notifications : Approval notifications',
    'Notifications : Signing notifications',
    'Notifications : SMTP notification',
    'Notifications : Notification preferences',
    'Task Centre : System Tasks',
    'Task Centre : Custom Tasks',
    'Task Centre : Legal Intake Tasks',
    'Others : Help Articles',
    'Others : Internal Documentation',
    'Others : Export Support Tickets',
    'Others : Mobile App',
    'Others : Browser Issue',
    'Others : Firewall/Proxy-setup',
    'Others : Cross-browser compatibility',
    'Others : Browser extenstions',
    'Others : Metabase Table Query',
    'Others : Feature Flags',
    'Others : VPN Issues',
    'Others : Run Postman Scripts',
    'Others : Billing Related CSM Query',
    'Others : No Context',
    'Others : Django Command',
    'Others : Cache Issue',
    'Others : Email domain Change',
    'Others : Email Change',
    'Others : Homepage',
    'Others : User Name Update',
    'Others : Obligation Management',
    'Others : Tray',
    'Template Changes : New Template Request',
    'Template Changes : Template Language update',
    'Template Changes : Template Computations',
    'Template Changes : Template Sign Blocks',
    'Template Changes : Draftmate Issues',
    'Template Changes : Template Condition Issue',
    'Template Changes : Template Dynamic Table Issues',
    'Template Changes : Formatting Issues',
    'Template Changes : Auto-Templatization',
    'Template Changes : Legacy Templates',
    'Editor : Only Office Issues',
    'Editor : Word Editor Issues',
    'Editor : Saved Changes Not reflecting',
    'Editor : Formatting Issues',
    'Editor : Comments and mentions',
    'Editor : Draftmate Issues',
    'Editor : VerifAI plugin in Word Editor Issues',
    'Personal Settings : Profile',
    'Personal Settings : Initials',
    'Personal Settings : Signature',
    'Personal Settings : Account Info',
    'Personal Settings : Change Password',
    'Workspace Profile : Workspace Logo',
    'Workspace Profile : Account Name',
    'Workspace Profile : Time and Date Settings',
    'Workspace Profile : Email Styling',
    'Entities : Create New Entity',
    'Entities : Delete Entity',
    'Entities : Edit Entity',
    'Entities : Email styling',
    'Entities : Entity Formats',
    'Entities : Seal',
    'Legal Intake : Legal Intake Creation',
    'Legal Intake : Task Creation',
    'Legal Intake : Workflow Creation',
    'Legal Intake : Set Up Questionnaire',
    'Legal Intake : Questionnaire Modifications',
    'Legal Intake : Create Intake from Slack',
    'Legal Intake : Legal Intake Analytics',
    'Finish Sign : OTP Delivery',
    'Finish Sign : Signature Execution / Formatting',
    'Finish Sign : Decline to Sign',
    'Finish Sign : Signed Document Download',
    'Finish Sign : Audit Trail',
    'Finish Sign : Embedded Signing',
    'Stamp Inventory : Delete stamps',
    'Stamp Inventory : Bulk upload stamps',
    'Stamp Inventory : Stamp status',
    'Stamp Inventory : Entity specific stamp setup',
    'Signing : Esign -Docusign',
    'Signing : Esign -Native',
    'Signing : Esign -Aadhar',
    'Sidebar : Enablement',
    'Sidebar : Login',
]

REQUEST_CATEGORIES = [
    'General FAQ - How to questions',
    'General FAQ - Misconfiguration',
    'General FAQ - API query',
    'General FAQ - Integration Query',
    'Workspace Creation - Sales Trial',
    'Workspace Creation - QA Workspace',
    'Workspace Creation - Duplicate Workspace',
    'Workspace Creation - Demo Access End Date',
    'Oncall - Oncall Tasks',
    'Oncall - Oncall bugs',
    'Oncall - Performance issues',
    'Oncall - Integration issues',
    'Oncall - Third-party dependency issue',
    'Feature Requests - Missing functionality',
    'Feature Requests - Enhancement to existing functionality',
    'Support Task - Manual Task',
    'Support Task - Script Run [Django]',
    'Support Task - Managerie Command Execution',
    'Support Task - Enable / Disable Feature Flag',
    'Legal - Template Changes',
    'Legal - Template Issues',
    'Global Outage - Global Outage / Downtime',
    'Others - Prospect request',
    'Others - Payments/Billing',
    'Others - Compliance Docs',
    'Others - No Context / Unknown Request',
]
